"""Stable machine-readable codes for structured parser→CRM observability (5A)."""

from __future__ import annotations

CRAWL_LISTING_SEEN = "CRAWL_LISTING_SEEN"
CRAWL_PRODUCT_PARSED = "CRAWL_PRODUCT_PARSED"
CRAWL_PRODUCT_PARTIAL = "CRAWL_PRODUCT_PARTIAL"
CRAWL_FAILURE = "CRAWL_FAILURE"
NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
NORMALIZATION_LOW_COVERAGE = "NORMALIZATION_LOW_COVERAGE"
LIFECYCLE_EVENT_SELECTED = "LIFECYCLE_EVENT_SELECTED"
LIFECYCLE_FALLBACK_APPLIED = "LIFECYCLE_FALLBACK_APPLIED"
DELIVERY_BATCH_STARTED = "DELIVERY_BATCH_STARTED"
DELIVERY_BATCH_COMPLETED = "DELIVERY_BATCH_COMPLETED"
DELIVERY_RETRY = "DELIVERY_RETRY"
CRM_APPLY_SUCCESS = "CRM_APPLY_SUCCESS"
CRM_APPLY_REJECTED = "CRM_APPLY_REJECTED"
CRM_APPLY_RETRYABLE = "CRM_APPLY_RETRYABLE"
CRM_APPLY_IGNORED = "CRM_APPLY_IGNORED"
CRM_IDS_PROPAGATED = "CRM_IDS_PROPAGATED"
RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
RECONCILIATION_RESOLVED = "RECONCILIATION_RESOLVED"
RECONCILIATION_UNRESOLVED = "RECONCILIATION_UNRESOLVED"
HEALTH_STATUS_CHANGED = "HEALTH_STATUS_CHANGED"
DUPLICATE_PAYLOAD_SKIPPED = "DUPLICATE_PAYLOAD_SKIPPED"

# --- Operational policy (5B) ---
THRESHOLD_BREACHED = "THRESHOLD_BREACHED"
STORE_STATUS_DEGRADED = "STORE_STATUS_DEGRADED"
STORE_STATUS_FAILING = "STORE_STATUS_FAILING"
RUN_STATUS_DEGRADED = "RUN_STATUS_DEGRADED"
RUN_STATUS_FAILING = "RUN_STATUS_FAILING"
ALERT_EMITTED = "ALERT_EMITTED"
INCIDENT_CLASSIFIED = "INCIDENT_CLASSIFIED"
STORE_ACTION_SUGGESTED = "STORE_ACTION_SUGGESTED"
RUN_ACTION_SUGGESTED = "RUN_ACTION_SUGGESTED"

# --- Operator support / triage / runbooks (5C) ---
TRIAGE_SUMMARY_BUILT = "TRIAGE_SUMMARY_BUILT"
RUNBOOK_PLAN_BUILT = "RUNBOOK_PLAN_BUILT"
SAFE_REPLAY_DECISION = "SAFE_REPLAY_DECISION"
DIAGNOSTIC_SNAPSHOT_BUILT = "DIAGNOSTIC_SNAPSHOT_BUILT"
OPERATOR_ACTION_RECOMMENDED = "OPERATOR_ACTION_RECOMMENDED"

# --- Release quality / test gates (6A) ---
RELEASE_GATE_EVALUATED = "RELEASE_GATE_EVALUATED"
RELEASE_CHECK_PASSED = "RELEASE_CHECK_PASSED"
RELEASE_CHECK_FAILED = "RELEASE_CHECK_FAILED"
CONTRACT_DRIFT_DETECTED = "CONTRACT_DRIFT_DETECTED"
STORE_ACCEPTANCE_GATE_FAILED = "STORE_ACCEPTANCE_GATE_FAILED"
RELEASE_READY = "RELEASE_READY"
RELEASE_BLOCKED = "RELEASE_BLOCKED"

# --- Rollout / feature flags (6B) ---
FEATURE_ROLLOUT_DECIDED = "FEATURE_ROLLOUT_DECIDED"
STORE_ROLLOUT_DECIDED = "STORE_ROLLOUT_DECIDED"
CANARY_BUCKET_SELECTED = "CANARY_BUCKET_SELECTED"
ROLLOUT_GUARD_BLOCKED = "ROLLOUT_GUARD_BLOCKED"
ROLLOUT_STAGE_PROMOTION_SUGGESTED = "ROLLOUT_STAGE_PROMOTION_SUGGESTED"
ROLLBACK_ADVICE_EMITTED = "ROLLBACK_ADVICE_EMITTED"
STORE_ENABLEMENT_DECIDED = "STORE_ENABLEMENT_DECIDED"

# --- Contract evolution / compatibility (6C) ---
COMPATIBILITY_CHECK_COMPLETED = "COMPATIBILITY_CHECK_COMPLETED"
BREAKING_CHANGE_DETECTED = "BREAKING_CHANGE_DETECTED"
DEPRECATION_WARNING_EMITTED = "DEPRECATION_WARNING_EMITTED"
SHADOW_FIELD_APPLIED = "SHADOW_FIELD_APPLIED"
DUAL_SHAPE_OUTPUT_BUILT = "DUAL_SHAPE_OUTPUT_BUILT"
MIGRATION_PLAN_BUILT = "MIGRATION_PLAN_BUILT"
MIGRATION_READINESS_REPORTED = "MIGRATION_READINESS_REPORTED"
COMPATIBILITY_GUARD_BLOCKED = "COMPATIBILITY_GUARD_BLOCKED"

# --- Security baseline / secrets / integrity (7A) ---
SECURITY_STARTUP_VALIDATED = "SECURITY_STARTUP_VALIDATED"
SECURITY_SECRET_LOADED = "SECURITY_SECRET_LOADED"
SECURITY_REQUEST_SIGNED = "SECURITY_REQUEST_SIGNED"
SECURITY_REDACTION_APPLIED = "SECURITY_REDACTION_APPLIED"
SECURITY_CONFIG_INVALID = "SECURITY_CONFIG_INVALID"
SECURITY_CONFIG_WARNING = "SECURITY_CONFIG_WARNING"

# --- Network safety / outbound controls (7B) ---
OUTBOUND_HOST_VALIDATED = "OUTBOUND_HOST_VALIDATED"
OUTBOUND_HOST_BLOCKED = "OUTBOUND_HOST_BLOCKED"
REDIRECT_BLOCKED = "REDIRECT_BLOCKED"
REDIRECT_ALLOWED = "REDIRECT_ALLOWED"
PROXY_VALIDATED = "PROXY_VALIDATED"
PROXY_BLOCKED = "PROXY_BLOCKED"
BROWSER_NAV_BLOCKED = "BROWSER_NAV_BLOCKED"
SSRF_GUARD_BLOCKED = "SSRF_GUARD_BLOCKED"
DOWNLOAD_GUARD_BLOCKED = "DOWNLOAD_GUARD_BLOCKED"

# --- Data minimization / operational hygiene (7C) ---
DATA_MINIMIZATION_APPLIED = "DATA_MINIMIZATION_APPLIED"
RETENTION_POLICY_APPLIED = "RETENTION_POLICY_APPLIED"
REPLAY_ABUSE_GUARD_BLOCKED = "REPLAY_ABUSE_GUARD_BLOCKED"
SUPPORT_SCOPE_RESTRICTED = "SUPPORT_SCOPE_RESTRICTED"
DIAGNOSTIC_EXPORT_MINIMIZED = "DIAGNOSTIC_EXPORT_MINIMIZED"
TRACE_RECORD_EXPIRED = "TRACE_RECORD_EXPIRED"
BUFFER_TRIMMED = "BUFFER_TRIMMED"

# --- Performance profiling / baseline (8A) ---
PERF_STAGE_TIMED = "PERF_STAGE_TIMED"
PERF_STAGE_SLOW = "PERF_STAGE_SLOW"
PERF_STORE_SNAPSHOT_BUILT = "PERF_STORE_SNAPSHOT_BUILT"
PERF_RUN_SNAPSHOT_BUILT = "PERF_RUN_SNAPSHOT_BUILT"
PERF_BOTTLENECK_DETECTED = "PERF_BOTTLENECK_DETECTED"
PERF_RESOURCE_SNAPSHOT = "PERF_RESOURCE_SNAPSHOT"

# --- Resource governance / scaling (8B) ---
RESOURCE_ADMISSION_ALLOWED = "RESOURCE_ADMISSION_ALLOWED"
RESOURCE_ADMISSION_BLOCKED = "RESOURCE_ADMISSION_BLOCKED"
BACKPRESSURE_APPLIED = "BACKPRESSURE_APPLIED"
RESOURCE_THROTTLE_ADJUSTED = "RESOURCE_THROTTLE_ADJUSTED"
BROWSER_BUDGET_EXCEEDED = "BROWSER_BUDGET_EXCEEDED"
PROXY_BUDGET_EXCEEDED = "PROXY_BUDGET_EXCEEDED"
BATCH_BACKPRESSURE_APPLIED = "BATCH_BACKPRESSURE_APPLIED"
STORE_DEGRADATION_SUGGESTED = "STORE_DEGRADATION_SUGGESTED"

# --- Cost / efficiency discipline (8C) ---
COST_SNAPSHOT_BUILT = "COST_SNAPSHOT_BUILT"
EFFICIENCY_SIGNAL_DETECTED = "EFFICIENCY_SIGNAL_DETECTED"
COST_REGRESSION_DETECTED = "COST_REGRESSION_DETECTED"
COST_REGRESSION_GATE_FAILED = "COST_REGRESSION_GATE_FAILED"
COST_REDUCTION_ACTION_SUGGESTED = "COST_REDUCTION_ACTION_SUGGESTED"

# --- Architecture / maintainability governance (9A) ---
ARCH_BOUNDARY_CHECK_COMPLETED = "ARCH_BOUNDARY_CHECK_COMPLETED"
ARCH_VIOLATION_DETECTED = "ARCH_VIOLATION_DETECTED"
ARCH_ANTI_PATTERN_DETECTED = "ARCH_ANTI_PATTERN_DETECTED"
CODE_PLACEMENT_DECIDED = "CODE_PLACEMENT_DECIDED"
MAINTAINABILITY_REPORT_BUILT = "MAINTAINABILITY_REPORT_BUILT"

# --- Developer experience / local workflow (9B) ---
DEV_MODE_ENABLED = "DEV_MODE_ENABLED"
DEV_DRY_RUN_ACTIVE = "DEV_DRY_RUN_ACTIVE"
DEV_FIXTURE_REPLAY_STARTED = "DEV_FIXTURE_REPLAY_STARTED"
DEV_DEBUG_SUMMARY_BUILT = "DEV_DEBUG_SUMMARY_BUILT"
DEV_LOCAL_SMOKE_COMPLETED = "DEV_LOCAL_SMOKE_COMPLETED"

# --- Documentation / knowledge continuity (9C) ---
DOCS_COVERAGE_CHECK_COMPLETED = "DOCS_COVERAGE_CHECK_COMPLETED"
OWNERSHIP_MAP_BUILT = "OWNERSHIP_MAP_BUILT"
STORE_PLAYBOOK_MISSING = "STORE_PLAYBOOK_MISSING"
KNOWLEDGE_CONTINUITY_REPORT_BUILT = "KNOWLEDGE_CONTINUITY_REPORT_BUILT"
DOCS_GOVERNANCE_GATE_FAILED = "DOCS_GOVERNANCE_GATE_FAILED"

# --- Production readiness (10A) ---
READINESS_EVIDENCE_COLLECTED = "READINESS_EVIDENCE_COLLECTED"
READINESS_GAP_DETECTED = "READINESS_GAP_DETECTED"
READINESS_STATUS_COMPUTED = "READINESS_STATUS_COMPUTED"
READINESS_REPORT_BUILT = "READINESS_REPORT_BUILT"
READINESS_BLOCKER_FOUND = "READINESS_BLOCKER_FOUND"

# --- Implementation roadmap (10B) ---
ROADMAP_ITEM_PLANNED = "ROADMAP_ITEM_PLANNED"
ROADMAP_DEPENDENCY_INFERRED = "ROADMAP_DEPENDENCY_INFERRED"
ROADMAP_CRITICAL_PATH_BUILT = "ROADMAP_CRITICAL_PATH_BUILT"
ROADMAP_REPORT_BUILT = "ROADMAP_REPORT_BUILT"
PHASE_ENTRY_BLOCKED = "PHASE_ENTRY_BLOCKED"
PHASE_EXIT_APPROVED = "PHASE_EXIT_APPROVED"
